USE ROLE SYSADMIN;
USE WAREHOUSE DEV_WH;
USE DATABASE DEV_DB;
USE SCHEMA DEV_SCHEMA;
CREATE OR REPLACE STAGE PDF_EXTERNAL
URL = "s3://sfquickstarts/Analyze PDF Invoices/Invoices/"
DIRECTORY = (ENABLE =TRUE);
SELECT * FROM DIRECTORY(@PDF_EXTERNAL);
LIST @PDF_EXTERNAL;
LS @PDF_EXTERNAL;